# Use the official Golang image as the base image (updated to Go 1.22.1)
FROM golang:1.22.1

# Set the working directory inside the container
WORKDIR /go/src/github/mlabouardy/movies-parser

# Set Go environment variables
ENV GOCACHE /tmp
ENV GO111MODULE=on

# Copy the entire source code to the working directory in the container
COPY . .

# Install dependencies
RUN go mod download

# Install golangci-lint for code linting
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

# Run the linter and exit on errors
RUN golangci-lint run ./...

# Build the Go app
RUN go build -o movies-parser .

# Command to run the application
CMD ["./movies-parser"]
