# Use the official Golang image as the base image
FROM golang:1.13.4

# Set the working directory inside the container
WORKDIR /go/src/github/mlabouardy/movies-parser

# Set Go environment variables
ENV GOCACHE /tmp
ENV GO111MODULE=on

# Copy the entire source code to the working directory in the container
COPY . .

# Install dependencies
RUN go mod download

# Install golangci-lint for code linting
RUN go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

# Run the linter and exit on errors
RUN golangci-lint run ./...

# Build the Go app
RUN go build -o movies-parser .

# Command to run the application
CMD ["./movies-parser"]
