FROM golang:1.13.4

# Set the working directory inside the container
WORKDIR /go/src/github/mlabouardy/movies-parser

# Set the Go build cache location
ENV GOCACHE /tmp

# Install golangci-lint (recommended Go linter tool)
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

# Copy the project files into the container
COPY . .

# Install all Go dependencies
RUN go get -v

# Run golangci-lint to perform linting checks on the code
RUN golangci-lint run ./...
